name: build-cosyvoice

on:
  workflow_dispatch:  # 수동 트리거 (Actions 탭에서 직접 실행 가능)

jobs:
  build-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: docker build
        run: |
          cd runtime/python
          docker build -t cosyvoice:1.0 .

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Tag image for ECR
        env:
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
        run: docker tag cosyvoice:v1.0 $ECR_REGISTRY/$ECR_REPOSITORY:1.0

      - name: Push image to ECR
        env:
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
        run: docker push $ECR_REGISTRY/$ECR_REPOSITORY:1.0
